# Generated by Django 6.0.2 on 2026-03-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Sang', 'Sang'), ('Medicament', 'Médicament'), ('Oxygene', 'Oxygène'), ('Couveuse', 'Couveuse')], max_length=32)),
                ('name_or_group', models.CharField(help_text='Nom de la ressource ou groupe sanguin', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Critique', 'Critique'), ('Rupture', 'Rupture')], max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='structures_app.structure')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
    ]
