# Generated by Django 6.0.2 on 2026-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_app', '0001_initial'),
        ('structures_app', '0002_disease_structures__name_e0403f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['structure', 'resource_type', 'status'], name='resources_a_structu_be1a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['last_updated'], name='resources_a_last_up_9f8c7f_idx'),
        ),
    ]
