# Generated by Django 6.0.2 on 2026-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources_app", "0002_resource_resources_a_structu_be1a3f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                help_text="Groupe sanguin (optionnel, principalement pour les ressources Sang).",
                max_length=3,
            ),
        ),
    ]
