# Generated by Django 6.0.2 on 2026-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='structures__name_e0403f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='structures__name_4a8392_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['is_active', 'type'], name='structures__is_acti_bc8807_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['is_active', 'name'], name='structures__is_acti_def6b8_idx'),
        ),
    ]
