# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("structures_app", "0002_disease_structures__name_e0403f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="structure",
            name="type",
            field=models.CharField(
                choices=[
                    ("Hopital", "Hôpital"),
                    ("Clinique", "Clinique"),
                    ("Pharmacie", "Pharmacie"),
                    ("Banque", "Banque de sang"),
                ],
                max_length=32,
            ),
        ),
    ]
