# Generated by Django 6.0.2 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("STRUCTURE_ADMIN", "Structure admin"),
                    ("ADMIN_STRUCTURE", "Admin structure"),
                    ("SUPER_ADMIN", "Super admin"),
                ],
                default="PUBLIC",
                help_text="Rôle de l'utilisateur dans la plateforme",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil de l'utilisateur.",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
