# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations


def normalize_structure_admin_role(apps, schema_editor):
    User = apps.get_model("users_app", "User")
    User.objects.filter(role="STRUCTURE_ADMIN").update(role="ADMIN_STRUCTURE")


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0002_user_profile_picture_and_role_alias"),
    ]

    operations = [
        migrations.RunPython(
            normalize_structure_admin_role,
            migrations.RunPython.noop,
        ),
    ]
